name: ROS2 Design
description: "Distilled design documents related to the ROS 2.0 effort"

baseurl: http://po-jen.github.io/design/
repo: https://github.com/Po-Jen/design/

oauth_client_id: efa6dd8eae9106381720

markdown: kramdown
highlighter: pygments

relative_permalinks: false

exclude:
 - CNAME
 - config.json
 - Gemfile
 - LICENSE
 - README.md
 - vendor
